/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Order = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'message' : IDL.Text,
  'eventDate' : IDL.Text,
  'eventType' : IDL.Text,
});
export const OrderId = IDL.Nat;

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [OrderId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Order = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'message' : IDL.Text,
    'eventDate' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [OrderId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };